### ISSUE TITLE
Duplication Glitch with EarthArmor/Plantarmor

### ISSUE THREAD

**Issue by LenderSchlender** [ProjectKorra/ProjectKorra#1129] opened 2021-02-06 16:40 UTC
If a Player dies while having EarthArmor or PlantArmor activated, and a Plugin lets them keep their Inventory (e.g. Towny protection or EssentialsX Keep Inventory permission), the Armor still get's dropped on the Ground, but it also stays in the Inventory of the Player

**Comment by MKieburtz** [comment] 2021-07-04 21:18
A similar issue happens with MetalClips

**Comment by Varhagna** [comment] 2021-07-05 05:04
Hello, sorry for the late response to this, we'll be sure to take a look and see whether this still persists in current versions.

**Comment by ChristopherWMM** [comment] 2021-08-22 18:36
After some investigation, it appears as though this issue is being caused by our PlayerDeathEvent listener being `NORMAL` while [Towny](https://github.com/TownyAdvanced/Towny/blob/81c2e91d2bd9cf567c9b51859f22c913fc0bee74/src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java#L860-L908) has theirs set to `HIGHEST` priority. This means our listener is running first before Towny has set keep inventory to `true`. [EssentialsX](https://github.com/EssentialsX/Essentials/blob/1e0d7fb0a3545d15c3b0cc1d180b47551f98cb22/Essentials/src/main/java/com/earth2me/essentials/EssentialsEntityListener.java#L191-L249) appears to have theirs set to `LOWEST` so that shouldn't be causing this issue. We may be able to fix this by modifying [our listener](https://github.com/ProjectKorra/ProjectKorra/blob/master/src/com/projectkorra/projectkorra/PKListener.java#L1019-L1075) to `MONITOR` priority.

**Comment by ChristopherWMM** [comment] 2021-08-22 18:42
This would be a good issue for anyone wanting to contribute, that being said, it will need to be thoroughly tested to ensure the event priority change doesn't have side effects.

**Comment by ChristopherWMM** [comment] 2021-08-22 19:46
@LenderSchlender @MKieburtz Are you able to replicate this issue with EarthArmor?

**Comment by MKieburtz** [comment] 2021-08-22 19:52
I'll set a reminder to try today

**Comment by ChristopherWMM** [comment] 2021-08-22 19:53
> I'll set a reminder to try today

Thanks, through some testing we were able to get Metal Clips to drop even with the EssentialsX keep inventory permission but not Earth Armor.

**Comment by MKieburtz** [comment] 2021-08-22 23:28
I was not able to replicate this issue with Earth Armor, by using Towny keep items on death in town on. Nor could I reproduce it with AngleChest, which puts items into a chest when you die.

**Comment by ChristopherWMM** [comment] 2021-08-23 00:05
> I was not able to replicate this issue with Earth Armor, by using Towny keep items on death in town on. Nor could I reproduce it with AngelChest, which puts items into a chest when you die.

Thanks for checking, I am going to backlog this issue for now unless any new information comes up about it.

**Comment by Shadow8472** [comment] 2021-09-30 09:48
Sorry about the duplicate. I had a zombie/husk drop a MetalClips iron chestplate today. No other plugins were installed. I almost certain I was running Spigot at the time, but it could have been Paper.

**Comment by JustAHuman-xD** [comment] 2023-03-24 15:41
Is this still an issue?

**Comment by MKieburtz** [comment] 2023-03-25 00:03
Unknown, I was never able to reproduce it, but you could try what @Shadow8472 did.

**Comment by MKieburtz** [comment] 2023-04-03 04:37
@JustAHuman-xD Actually I just tried this again and successfully reproduced this with plant armor. My server setup uses the plugin angelchest to create a chest with your items when you die. This may or may not be related. Steps:

- install angelchest. I don't think you'll need any configuration, but you could test that an angel chest spawns when you die.
- Equip some armor
- Activate plant armor
- Die
- your armor will stay on your body even though you died, as well as be dropped in your death spot. The plant armor will be in the angel chest too (this I'm not too worried about). We do not have keep inventory on, so the armor staying on your body even when you die must be because of PlantArmor.

I know plant armor is not from PK, but perhaps try these steps with earth armor and see what happens.

**Comment by StrangeOne101** [comment] 2024-05-13 08:15
To bring this up again, does this still happens with PlantArmor? With EarthArmor?

**Comment by MKieburtz** [comment] 2024-05-13 19:48
Oh no I should have followed up, this was a misconfiguration with Anglechest.

**Comment by StrangeOne101** [comment] 2024-05-14 00:32
Perfect. So it's good to close then?

**Comment by StrangeOne101** [comment] 2024-06-28 05:22
Closed since it seems to be resolved

**Closed by StrangeOne101** 2024-06-28 05:22 UTC
Labels: Bug
