### ISSUE TITLE
Extraction Doesn't Work on Copper

### ISSUE THREAD

**Issue by Shadow8472** [ProjectKorra/ProjectKorra#1177] opened 2021-09-30 19:14 UTC
While Copper is ignored by EarthTunnel when configured to ignore ores, extraction can't do anything with it once exposed.

**Comment by Dooder07** [comment] 2021-10-01 01:48
This will be fixable by as soon as when the next major update releases, which is when the Bukkit API will be bumped.

**Comment by MKieburtz** [comment] 2021-10-02 18:22
Yeah this can probably be closed because PK simply doesn't make use of the 1.17 API yet. If this is still an issue after they do then it could be reopened though.

**Comment by ChristopherWMM** [comment] 2021-10-02 20:01
Hello, as described above, this is currently intended behavior. Our API version is still on 1.16 but that will be changing soon. I am going to leave this issue open until it is resolved but it will for sure be part of a future release.

**Comment by MKieburtz** [comment] 2021-12-29 22:28
Can this be closed now @ChristopherWMM?

**Comment by ChristopherWMM** [comment] 2021-12-29 23:07
> Can this be closed now @ChristopherWMM?

Unfortunately not; however, we are now able to bump the API version enabling this issue to be fixed.

**Comment by ChristopherWMM** [comment] 2022-06-03 02:29
Fixed as of #1205

**Closed by ChristopherWMM** 2022-06-03 02:29 UTC
Labels: Confirmed
